"""
Django settings for exam\_portal project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
[https://docs.djangoproject.com/en/5.2/topics/settings/](https://docs.djangoproject.com/en/5.2/topics/settings/)

For the full list of settings and their values, see
[https://docs.djangoproject.com/en/5.2/ref/settings/](https://docs.djangoproject.com/en/5.2/ref/settings/)
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE\_DIR / 'subdir'.

BASE\_DIR = Path(**file**).resolve().parent.parent

# Quick-start development settings - unsuitable for production

# See [https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/](https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/)

# SECURITY WARNING: keep the secret key used in production secret!

SECRET\_KEY = 'django-insecure-\$tk-0y&1f22%l&5li8i1n^d-9om3m-%r\@elq=hp43q=f\&wq86@'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED\_HOSTS = \['localhost', '192.168.1.20', 'examination-portal-7396.onrender.com']

# Application definition

INSTALLED\_APPS = \[
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'core',
]

MIDDLEWARE = \[
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT\_URLCONF = 'exam\_portal.urls'

TEMPLATES = \[
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': \[BASE\_DIR / "core" / "templates"],
'APP\_DIRS': True,
'OPTIONS': {
'context\_processors': \[
'django.template.context\_processors.request',
'django.contrib.auth.context\_processors.auth',
'django.contrib.messages.context\_processors.messages',
],
},
},
]

WSGI\_APPLICATION = 'exam\_portal.wsgi.application'

# Database

# [https://docs.djangoproject.com/en/5.2/ref/settings/#databases](https://docs.djangoproject.com/en/5.2/ref/settings/#databases)

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.sqlite3',
'NAME': BASE\_DIR / 'db.sqlite3',
}
}

# Password validation

# [https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators](https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators)

AUTH\_PASSWORD\_VALIDATORS = \[
{
'NAME': 'django.contrib.auth.password\_validation.UserAttributeSimilarityValidator',
},
{
'NAME': 'django.contrib.auth.password\_validation.MinimumLengthValidator',
},
{
'NAME': 'django.contrib.auth.password\_validation.CommonPasswordValidator',
},
{
'NAME': 'django.contrib.auth.password\_validation.NumericPasswordValidator',
},
]

# Internationalization

# [https://docs.djangoproject.com/en/5.2/topics/i18n/](https://docs.djangoproject.com/en/5.2/topics/i18n/)

LANGUAGE\_CODE = 'en-us'

TIME\_ZONE = 'UTC'

USE\_I18N = True

USE\_TZ = True

# Static files (CSS, JavaScript, Images)

# [https://docs.djangoproject.com/en/5.2/howto/static-files/](https://docs.djangoproject.com/en/5.2/howto/static-files/)

STATIC\_URL = 'static/'
STATICFILES\_DIRS = \[
os.path.join(BASE\_DIR, 'core/static'),
]

# Default primary key field type

# [https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field](https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field)

DEFAULT\_AUTO\_FIELD = 'django.db.models.BigAutoField'

LOGIN\_URL = '/accounts/login/'  # Ensure this is set
LOGIN\_REDIRECT\_URL = 'profile'  # Redirect to profile after login
